baseURL = "https://oxfordrse.github.io/streamlit"

# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Streamlit workshop"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Sections"
    url = "posts"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "about"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true


[params]
  # LoveIt theme version
  version = "0.2.X"

[params.header]
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Streamlit Workshop"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = "<i class=\"fas fa-code\"></i>"
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

[params.page.mapbox]
  # access token of Mapbox GL JS
  accessToken = "pk.eyJ1IjoiZmVyZ3VzY29vcGVyIiwiYSI6ImNrbXRudWpyMDB0cnkydnBtbWU5NXRrY28ifQ.0plSQ66uhgbhkhmeCnlqoQ"
  # style for the light theme
  lightStyle = "mapbox://styles/mapbox/light-v10"
  # style for the dark theme
  darkStyle = "mapbox://styles/mapbox/dark-v10"
  # whether to add NavigationControl
  navigation = true
  # whether to add GeolocateControl
  geolocate = true
  # whether to add ScaleControl
  scale = true
  # whether to add FullscreenControl
  fullscreen = true

[params.page.toc]
  # whether to enable the table of the contents
  enable = true
  # LoveIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
  keepStatic = true
  # whether to make the table of the contents in the sidebar automatically collapsed
  auto = false
